feat: 完成前端首頁，並且串接後端 api
rdcvgt/Taipei-Day-Trip pull request #2
Opened 2022-11-21 16:32 UTC by rdcvgt

1. 完成 RWD 靜態頁面
2. 串接景點 API，並展示第一頁的景點資訊
3. 完成自動載入後續頁面的功能
4. 完成關鍵字搜尋功能
5. 完成景點分類關鍵字填入功能

姓名：彭勝緯
網址：http://13.112.131.32:3000/
再麻煩老師了謝謝！

2022-11-22 13:13 UTC, cwpeng requested changes
1. Your page loads all the attraction data even if I never scroll down to the page bottom.
2. You always clear and rebuild all attraction blocks when loading new data, it's much better to append new attraction block to the bottom.

2022-11-22 17:52 UTC, rdcvgt commented
老師好，已經針對兩個問題進行修正，再麻煩了，謝謝！

2022-11-23 06:36 UTC, cwpeng approved these changes
Good. Done.

2022-11-23 06:43 UTC, merged

2022-11-23 06:45 UTC, rdcvgt commented
謝謝老師～